### ISSUE TITLE
Can find by pip install.

### ISSUE THREAD

**Issue by joaolucasmacedo** [wutcat/netbox-nas#1]
Hi.
I can't find it using "pip install netbox-nas". 
Does it use a different name?
It would be nice to have a short installation guide.

**Comment by wutcat** [comment]
Yo!
I haven't published this to PyPI yet but can do. Will advise.
In the meantime, you can install using the package URL `pip install https://github.com/wutcat/netbox-nas/releases/download/v1.0.0/netbox_nas-1.0.0-py3-none-any.whl`

**Comment by wutcat** [comment]
There's now a workflow to build and upload to PyPI. Closing out.
